all: create_random_image process_image 

create_random_image: create_random_image.cpp 
	g++ -o create_random_image create_random_image.cpp

process_image: process_image.cpp
	g++ -o process_image process_image.cpp
