all: create_random_image process_image dim_tester

create_random_image: create_random_image.cpp 
	g++ -o create_random_image create_random_image.cpp

process_image: process_image.cpp
	g++ -o process_image process_image.cpp

dim_tester: dim_tester.cpp
	g++ -o dim_tester dim_tester.cpp