# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat.xci
# IP: The module: 'fifo_generator_2048_32_no_lat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2048_32_no_lat'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2048_32_no_lat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat.xci
# IP: The module: 'fifo_generator_2048_32_no_lat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2048_32_no_lat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/georgepag4028/Desktop/Sxoli/Vlsi2021/Ask5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/ip/fifo_generator_2048_32_no_lat/fifo_generator_2048_32_no_lat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2048_32_no_lat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
